# Generated by Django 4.2.7 on 2023-11-21 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='records',
            old_name='last_nmae',
            new_name='last_name',
        ),
    ]
